services:
  # Servicio para la API
  api-smartpot:
    image: sebastian190030/api-smartpot:latest
    container_name: smartpot-api
    ports:
      - "8091:8091"
    env_file:
      - .env.api
    networks:
      - network
    labels:
      "docker_compose_diagram.icon": "api"
      "docker_compose_diagram.cluster": "Backend Layer"
      "docker_compose_diagram.description": "API REST"

  # Servicio para la aplicación web
  web-smartpot:
    image: sebastian190030/web-smartpot:latest
    container_name: smartpot-web
    ports:
      - "5173:5173"
    depends_on:
      - api-smartpot
    env_file:
      - .env.web
    networks:
      - network
    labels:
      "docker_compose_diagram.icon": "react"
      "docker_compose_diagram.cluster": "Frontend Layer"
      "docker_compose_diagram.description": "Web App"

# Red compartida
networks:
  network:
    driver: bridge