---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-smartpot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-smartpot
  template:
    metadata:
      labels:
        app: db-smartpot
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-smartpot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-smartpot
  template:
    metadata:
      labels:
        app: api-smartpot
    spec:
      containers:
        - name: api-container
          image: smartpot/api:latest
          ports:
            - containerPort: 8091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-smartpot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-smartpot
  template:
    metadata:
      labels:
        app: web-smartpot
    spec:
      containers:
        - name: web-container
          image: smartpot/web:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: db-smartpot
  namespace: default
spec:
  type: NodePort
  selector:
    app: db-smartpot
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: api-smartpot
  namespace: default
spec:
  type: NodePort
  selector:
    app: api-smartpot
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: web-smartpot
  namespace: default
spec:
  type: NodePort
  selector:
    app: web-smartpot
  ports:
    - port: 80
      targetPort: 5173
      protocol: TCP
      nodePort: 30002
