apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-smartpot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-smartpot
  template:
    metadata:
      labels:
        app: db-smartpot
    spec:
      containers:
        - name: db-smartpot
          image: sebastian190030/db-smartpot:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db-smartpot
spec:
  selector:
    app: db-smartpot
  ports:
    - protocol: TCP
      port: 27017       # Puerto expuesto por el servicio
      targetPort: 27017 # Puerto del contenedor MongoDB
  type: NodePort
  nodePort: 30000        # Puerto externo para acceso desde fuera de Minikube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-smartpot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-smartpot
  template:
    metadata:
      labels:
        app: api-smartpot
    spec:
      containers:
        - name: api-smartpot
          image: sebastian190030/api-smartpot:latest
          env:
            - name: APP_NAME
              value: "SmartPot-API"
            - name: PORT
              value: "8091"
            - name: TITLE
              value: "SmartPot API"
            - name: DESCRIPTION
              value: "Documentación de la API REST de SmartPot"
            - name: VERSION
              value: "1.0.0"
            - name: AUTHOR
              value: "SmartPot Developers"
            - name: DATA_CONNECTION_METHOD
              value: "mongodb"
            - name: DATA_SOURCE_USERNAME
              value: "admin"
            - name: DATA_SOURCE_PASSWORD
              value: "admin"
            - name: DATA_SOURCE_DOMAIN
              value: "db-smartpot:27017" # Nombre del servicio de MongoDB
            - name: DATA_SOURCE_DB
              value: "smartpot"
            - name: DATA_PARAMS
              value: "authSource=admin&directConnection=true&serverSelectionTimeoutMS=100000&socketTimeoutMS=10000&appName=mongo"
            - name: SECURITY_JWT_SECRET_KEY
              value: "c8e9b6803afbcfa6edd9569c94c75ff4b144622b0a0570a636dffd62c24a3476"
            - name: SECURITY_JWT_EXPIRATION
              value: "86400000"
            - name: SECURITY_PUBLIC_ROUTES
              value: "/auth/login,/auth/verify"
            - name: HEADER_CORS_ALLOWED_ORIGINS
              value: "http://localhost:5173"
            - name: SERVER_TOMCAT_TIMEOUT
              value: "600000"
            - name: DEBUGGER_MODE
              value: "INFO"
          ports:
            - containerPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: api-smartpot
spec:
  selector:
    app: api-smartpot
  ports:
    - protocol: TCP
      port: 8091       # Puerto expuesto por el servicio
      targetPort: 8091 # Puerto del contenedor API
  type: NodePort
  nodePort: 30001      # Puerto externo para acceso desde fuera de Minikube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-smartpot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-smartpot
  template:
    metadata:
      labels:
        app: web-smartpot
    spec:
      containers:
        - name: web-smartpot
          image: sebastian190030/web-smartpot:latest
          env:
            - name: VITE_API_BASE_URL
              value: "http://api-smartpot:8091" # URL del servicio de la API
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: web-smartpot
spec:
  selector:
    app: web-smartpot
  ports:
    - protocol: TCP
      port: 80         # Puerto expuesto por el servicio web
      targetPort: 5173 # Puerto del contenedor web
  type: NodePort
  nodePort: 30002      # Puerto externo para acceso desde fuera de Minikube
